[package]
name = "littify-repl"
version = "0.1.1"
authors = ["Spaceface16518 <33424649+Spaceface16518@users.noreply.github.com>"]
edition = "2015"

[dependencies]
littify-core = { path = "../littify-core" }

[[bin]]
name = "littify-repl"
path = "src/bin/main.rs"
